### ISSUE TITLE
[Bug] Vencord setting section no longer visible, issue is fixed upstream

### ISSUE THREAD

**Issue by net-wayfarer** [Davilarek/Vencord#11]
### What happens when the bug or crash occurs?

* ### Where does this bug occur
Under user settings there should be a section titled Vencord, and these allow users to configure Vencord, especially virtual filesystem for BetterVencord.

* ### When does it occur
Whenever discord is started.

### What is the expected behaviour?

Vencord settings should be visible.

### How do you recreate this bug or crash?

1. Run BetterVencord as you normally do,
2. Go into User settings,
3. Note the Vencord section is completely missing

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

### Versions:
Discord: stable 293362 (73826fe)
BetterVencord: 07264aaea1cef4e2db7488b7480bd283f493aeda
Electron: 28.2.10
Chromium: 120.0.6099.291
Host 0.0.53 x64
OpenAsar Nightly (4f264d8)
Linux 64-bit (6.8.7-arch1-1)

### Notes:
This was fixed upstream in multiple commits (oldest possibly related commit first):
* https://github.com/Vendicated/Vencord/commit/0e4724ec0d2ee3c9bd15f81d29dcbd8fec1211ce
* https://github.com/Vendicated/Vencord/commit/719c6140f3fafb0ae04323268651f0b4f919af91
* https://github.com/Vendicated/Vencord/commit/12376c622ee1568d7c4633272362534ca7aea2df

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Davilarek** [comment]
Should be fixed now
