### ISSUE TITLE
what plugins have been confirmedto work and is one of them split large files 

### ISSUE THREAD

**Issue by Pickymarker** [Davilarek/Vencord#14]
### Content

what plugins have been confirmed to work and is one of them split large files 

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Davilarek** [comment]
Possibly most of BD plugins. Including but not limited to: MLv2, ZeresPluginLib, (most if not all) DevilBro plugins (I tested BDFDB, PluginRepo and some more I don't remember), InAppNotifications, NotificationSounds, AssignBadgesRewrite

I have not tested SplitLargeFiles.

**Comment by Davilarek** [comment]
does that answer your question?

**Comment by Pickymarker** [comment]
yes
