### ISSUE TITLE
Would you ever add Reppluged plugin support

### ISSUE THREAD

**Issue by Pickymarker** [Davilarek/Vencord#15]
### Content

Would you ever add Reppluged plugin support

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Davilarek** [comment]
Why

**Comment by Pickymarker** [comment]
because certain people only develop plugins for Repplugged and might as well have support for all client plugins

**Comment by nin0-dev** [comment]
> because certain people only develop plugins for Repplugged and might as well have support for all client plugins

1- most bd plugins are covered by vencord plugins, which leaves the bdcompat layer only for some niche plugins
2- likely that if a replugged plugin was made its bd counterpart was made

which makes a replugged compat layer useless

**Comment by Pickymarker** [comment]
but the thing is there is some plugins that are replugged only and I have checked

**Comment by zrodevkaan** [comment]
We are not adding Replugged support. It defeats the purpose of **Better**Vencord.

**Comment by Pickymarker** [comment]
how does it defeat the purpose why wouldn't you want the 3 best client mods in one

**Comment by zrodevkaan** [comment]
BetterVencord is a combination of Vencord and BetterDiscord. Made for BetterDiscord plugins but in Vencord for faster loading speeds. We are not supporting Replugged.
