### ISSUE TITLE
Could you make yabdp4nitro and splitlargefiles both by riolubruh work with this 

### ISSUE THREAD

**Issue by Cxsmo-ai** [Davilarek/Vencord#17]
### Content

Could you make yabdp4nitro and splitlargefiles both by riolubruh work with this https://github.com/riolubruh/SplitLargeFiles https://github.com/riolubruh/YABDP4Nitro

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Davilarek** [comment]
What is the issue

**Comment by Pickymarker** [comment]
they don't show up in vencord plugins to enable after adding

**Comment by Pickymarker** [comment]
okay so here is split large files 
[canary.discord.com-1720270109690.txt](https://github.com/user-attachments/files/16116172/canary.discord.com-1720270109690.txt)

**Comment by Davilarek** [comment]
You installed BV as userPlugin. It will *NOT* work as standalone userPlugin.

**Comment by Pickymarker** [comment]
what do i need for it to work fully

**Comment by Davilarek** [comment]
Install as Vencord replacement. Everything is in README.

**Comment by Pickymarker** [comment]
just did didn't help

**Comment by Davilarek** [comment]
Not as a userPlugin?

**Comment by Pickymarker** [comment]
no i did your full install and i didn't help

**Comment by Davilarek** [comment]
Send log again

**Comment by Pickymarker** [comment]
to show i am on your version 
![image](https://github.com/Davilarek/Vencord/assets/74084396/f1a88905-4262-4e1c-8f75-79057c801dbf)

**Comment by Pickymarker** [comment]
splitlargefiles 
[canary.discord.com-1720271737570.txt](https://github.com/user-attachments/files/16116235/canary.discord.com-1720271737570.txt)

**Comment by Davilarek** [comment]
```
pluginConstructor.ts:246 Something snapped during parsing of meta for file: 0PluginLibrary.plugin.js The error got triggered after 0-nth line of meta The error was: TypeError: Cannot read properties of undefined (reading 'split')
    at a (pluginConstructor.ts:242:46)
    at Hi (pluginConstructor.ts:324:5)
    at index.ts:423:17
a @ pluginConstructor.ts:246
```
You need to install ZeresPluginLib properly as right now its invalid

**Comment by Pickymarker** [comment]
splitlargefiles

[canary.discord.com-1720271890591.txt](https://github.com/user-attachments/files/16116247/canary.discord.com-1720271890591.txt)

**Comment by Pickymarker** [comment]
splitlarge files after doing what you said 
[canary.discord.com-1720272233711.txt](https://github.com/user-attachments/files/16116265/canary.discord.com-1720272233711.txt)

**Comment by Pickymarker** [comment]
yabdp4nitro with zeres enabled in plugins and also doing that same thing still didn't make splitlargefiles work
[canary.discord.com-1720272398122.txt](https://github.com/user-attachments/files/16116274/canary.discord.com-1720272398122.txt)

**Comment by Pickymarker** [comment]
the plugins just don't show up in vencord plugins to enable but they show up fine in the virtual file system

**Comment by zrodevkaan** [comment]
Have you ever considered that `SplitLargeFiles` doesnt work anymore? One search would of give you your answer.

@Davilarek `Webpack.getByPrototypeKeys` does this exist within vencord?

**Comment by zrodevkaan** [comment]
Yeah. `getByPrototypeKeys` does not exist. Either wait for Davilarek to add it or don't use it at all.

**Comment by Pickymarker** [comment]
okay then splitlargefiles is a no then but for yabdp4nitro i know that works on betterdiscord because tested it

**Comment by zrodevkaan** [comment]
I'm not giving support for a stereo plugin. As I said. `yabdp4nitro` is a BV issue. Wait for a fix.

**Comment by Pickymarker** [comment]
okay i get not wanting stereo and so just yabdp4nitro is good then because of all the stuff it can do and its needed because philhk better screenshare for vencord has crashing problems

**Comment by Pickymarker** [comment]
and true for stereo you don't even need a client mod to do

**Comment by Davilarek** [comment]
I'll fix in 10 minutes

**Comment by Davilarek** [comment]
let me know if https://github.com/Davilarek/Vencord/commit/a907d7c379f25fe2ffc774cefc1068c9922fb8b4 fixes your issue

**Comment by Davilarek** [comment]
@Pickymarker

**Comment by Davilarek** [comment]
Closing this because no response. Will reopen if needed.

**Comment by Pickymarker** [comment]
none of screenshare stuff works

**Comment by Davilarek** [comment]
Are there any errors in console during screenshare?

**Comment by Davilarek** [comment]
btw FakeNitro from Vencord already unlocks screenshare nitro quality so `yabdp4nitro` is not needed. Closing this as FakeNitro will work better on BetterVencord than yabdp4nitro does anyway.
