### ISSUE TITLE
Could you make yabdp4nitro and splitlargefiles both by riolubruh work with this and am using your vencord install following your instructions 

### ISSUE THREAD

**Issue by Pickymarker** [Davilarek/Vencord#18]
### Content

Could you make yabdp4nitro and splitlargefiles both by riolubruh work with this and am using your vencord install following your instructions https://github.com/riolubruh/SplitLargeFiles https://github.com/riolubruh/YABDP4Nitro

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Ansemik** [comment]
No

**Comment by Pickymarker** [comment]
why

**Comment by zrodevkaan** [comment]
Duplicate Issue

**Comment by Pickymarker** [comment]
i posted it again because he closed my issue when my problem was not fixed

**Comment by zrodevkaan** [comment]
I did not mean to reopen this.

**Comment by zrodevkaan** [comment]
Stop opening post. You continued to talk after it was closed and still decided to make a new post. Stop

**Comment by Pickymarker** [comment]
i followed everything he said to do in  my last post and still doesn't work those plugins
