### ISSUE TITLE
[Bug] Vencord setting section no longer visible, issue is fixed upstream

### ISSUE THREAD

**Issue by net-wayfarer** [Davilarek/Vencord#9]
### What happens when the bug or crash occurs?

* ### Where does this bug occur
Under user settings there should be a section titled Vencord, and these allow users to configure Vencord, especially virtual filesystem for BetterVencord.

* ### When does it occur
Whenever discord is started.

### What is the expected behaviour?

Vencord settings should be visible.

### How do you recreate this bug or crash?

1. Run BetterVencord as you normally do,
2. Go into User settings,
3. Note the Vencord section is completely missing

### Errors

Unfortunately I am unsure of which errors were related to this, but can confirm that the upstream commit/patch fixes this issue, please continue reading.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

### Versions:
Discord: stable 285561 (e592eef)
BetterVencord: 26ab2929f4fe7d33594a60fdfdc5e7112bdd3a2f
Electron: 28.2.10
Chromium: 120.0.6099.291
Host 0.0.50 x64
OpenAsar Nightly (4f264d8)
Linux 64-bit (6.8.5-arch1-1)

### Notes:
This was fixed upstream: https://github.com/Vendicated/Vencord/commit/89c82e2cd173b26b0eee938022afad5684e174cd

**Comment by Davilarek** [comment]
Fixed in cd94d58
